-- select * from users
-- select username, password from users
-- insert into users (username, password) values('tony', '098')
-- update users set password='888888' where id=3
-- update users set password='admin12', status=1 where id=2
-- delete from users where id=4
-- select * from users where id>2
-- select * from users order by id desc
-- select * from users order by status, username desc
-- select count(*) as total from users where status = 0